### ISSUE TITLE
In Blender 3.4 I get an error when installing How can I solve this?

### ISSUE THREAD

**Issue by gkcc0625** [JulienHeijmans/quicksnap#1]
In Blender 3.4
I get an error when installing
How can I solve this?

Traceback (most recent call last):
  File "D:\TEST\blender-3.4.0 Alpha\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\01020\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\quicksnap-main\__init__.py", line 41, in register
    sys.modules[current_module_name].register()
TypeError: register() missing 1 required positional argument: 'bl_info'

**Comment by JulienHeijmans** [comment]
Thank you for reporting the issue! It was a mistake on my part.
It should be fixed now, if you download the zip file again. ([https://github.com/JulienHeijmans/quicksnap/archive/refs/heads/main.zip](https://github.com/JulienHeijmans/quicksnap/archive/refs/heads/main.zip))

Click"Remove" in the addon settings of QuickSnap before to make sure the old version is uninstalled.

**Comment by gkcc0625** [comment]
Wow!!!
thanks to your hard work...
installation went well
Thank you and I will use it happily
I envy your abilities
The ability to do this...
