### ISSUE TITLE
Error spam when using unexpected key map for the tool (eg: backslash)

### ISSUE THREAD

**Issue by JulienHeijmans** [JulienHeijmans/quicksnap#28]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_ui\space_userpref.py", line 2051, in draw
    draw(context)
  File "C:\Users\<me>\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap\quicksnap.py", line 871, in draw
    quicksnap_utils.insert_ui_hotkey(col, f'EVENT_{quicksnap_keymap.type}',
  File "C:\Users\<me>\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap\quicksnap_utils.py", line 292, in insert_ui_hotkey
    row.label(text="", icon=key)
TypeError: UILayout.label(): error with keyword argument "icon" -  enum "EVENT_BACK_SLASH" not found in ('NONE', 'QUESTION', 'ER

**Comment by JulienHeijmans** [comment]
Solved on main
